services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  db:
    driver: local
  redis:
    driver: local