// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignTask = `-- name: AssignTask :exec
UPDATE tasks SET user_id = $1, updated_at = NOW()
WHERE id = $2
`

type AssignTaskParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) AssignTask(ctx context.Context, arg AssignTaskParams) error {
	_, err := q.db.Exec(ctx, assignTask, arg.UserID, arg.ID)
	return err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title,description,team_id)
VALUES($1, $2, $3)
RETURNING id, title, description, status, team_id, user_id, created_at, updated_at
`

type CreateTaskParams struct {
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	TeamID      pgtype.UUID `json:"team_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Title, arg.Description, arg.TeamID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.TeamID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, title, description, status, team_id, user_id, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.TeamID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, status, team_id, user_id, created_at, updated_at FROM tasks 
WHERE team_id = $1
`

func (q *Queries) ListTasks(ctx context.Context, teamID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.TeamID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTask = `-- name: RemoveTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) RemoveTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, removeTask, id)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateTaskStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
