// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTeamMember = `-- name: AddTeamMember :exec
INSERT INTO team_members (user_id,team_id)
VALUES ($1,$2)
`

type AddTeamMemberParams struct {
	UserID pgtype.UUID `json:"user_id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) error {
	_, err := q.db.Exec(ctx, addTeamMember, arg.UserID, arg.TeamID)
	return err
}

const getTeamMembers = `-- name: GetTeamMembers :many
SELECT u.id, u.name, u.email, u.password, u.created_at, u.updated_at FROM users u 
JOIN team_members tm ON u.id = tm.user_id 
WHERE tm.team_id = $1
`

func (q *Queries) GetTeamMembers(ctx context.Context, teamID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getTeamMembers, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamsByUser = `-- name: GetTeamsByUser :many
SELECT t.id, t.name, t.description, t.owner_id, t.created_at, t.updated_at FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = $1
`

func (q *Queries) GetTeamsByUser(ctx context.Context, userID pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, getTeamsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE user_id = $1 AND team_id = $2
`

type RemoveTeamMemberParams struct {
	UserID pgtype.UUID `json:"user_id"`
	TeamID pgtype.UUID `json:"team_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.Exec(ctx, removeTeamMember, arg.UserID, arg.TeamID)
	return err
}
